In [1]:
import numpy as np
import matplotlib.pyplot as plt
import inspect
import re
    
def show_loss_on_distribution(distribution, w, loss):
    plt.plot(distribution, 'g-')
    plt.plot(w, loss, 'rx')
    plt.show()

def show_gradient_on_distribution(distribution, w, loss, gradient):
    plt.plot(distribution, 'g-')
    plt.arrow(w, loss, 1, gradient, width=0.2, color="red", length_includes_head=True)
    plt.show()

def print_vars(*variables):
    for index in range(len(variables)):
        frame = inspect.currentframe().f_back
        s = inspect.getframeinfo(frame).code_context[0]
        r = re.search(r"\((.*)\)", s).group(1)
        print("{} = {}".format(r.split(", ")[index],variables[index]))

In [59]:
# y = x * w + 1 * b

x1 = np.expand_dims(np.arange(4), 1)
x2 = np.expand_dims(np.arange(4) + 10, 1)
x = np.hstack((x1, x2))
y1 = x1 + x2 > 12
y2 = x1 + x2 <= 12
y = np.hstack((y1, y2))

ones = np.ones((x.shape[0], 1))
x = np.hstack((x, ones))

print_vars(x, y)

x = [[ 0. 10.  1.]
 [ 1. 11.  1.]
 [ 2. 12.  1.]
 [ 3. 13.  1.]]
y = [[False  True]
 [False  True]
 [ True False]
 [ True False]]


In [60]:
# loss(activate(multiply(w, x), y))

def multiply(x, w):
    # x = 4x2
    # w = 2x1
    return np.matmul(x, w) # 4x1

def calculate_d_multiply(x, w):
    return x # 4x2

def activate(x):
    return 1 / (1 + np.exp(-x))

def calculate_d_activate(x):
    return activate(x) * (1 - activate(x))

def calculate_loss(prediction, y):
    return np.mean(np.power(prediction - y, 2)) # 1x1 -> sum(n1,n2,n2)/ n

def calculate_d_loss(prediction, y):
    return 2 * (prediction - y) / y.shape[0] # 4x1

def train(x, y, learning_rate, steps):
    w = np.zeros((x.shape[1], y.shape[1]))
    for i in range(steps):
        # forward
        multiplication = multiply(x, w) # 4x1
        prediction = activate(multiplication) # 4x1

        # calculation of error
        loss = calculate_loss(prediction, y) # 1x1

        # backpropagation
        d_multiply = calculate_d_multiply(x, w) # 4x2 --> 2x4
        d_activate = calculate_d_activate(multiplication)
        d_loss = calculate_d_loss(prediction, y) # 4x1

        gradient = np.matmul(d_multiply.T, d_loss * d_activate) # 2x1 

        w = w - gradient * learning_rate
    return w

w = train(x, y, 0.1, 10000)
prediction = activate(multiply(x, w))
print_vars(x, prediction, y, w)

x = [[ 0. 10.  1.]
 [ 1. 11.  1.]
 [ 2. 12.  1.]
 [ 3. 13.  1.]]
prediction = [[2.23344509e-04 9.99776655e-01]
 [5.81567049e-02 9.41843295e-01]
 [9.44652010e-01 5.53479905e-02]
 [9.99788072e-01 2.11928372e-04]]
y = [[False  True]
 [False  True]
 [ True False]
 [ True False]]
w = [[ 6.39093128 -6.39093128]
 [-0.76905729  0.76905729]
 [-0.71599886  0.71599886]]
